project:
  type: website

website:
  title: "Sasipimt"
  reader-mode: true
  navbar:
    background: primary
    title: false
    search: true
    left:
      - text: "Home"
        href: index.qmd
    tools:
      - icon: github
        href: https://github.com/sasipimt/blog
  site-url: "https://sasipimt.github.io/blog/"

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
